[package]
name = "bmpow"
version = "0.1.0"
authors = ["Gergely Imreh <imrehg@gmail.com>"]

[dependencies]
byteorder = "^0.4"
num_cpus = "^0.2"
rust-crypto = "^0.2"

[lib]
name = "bmpow"
crate-type = ["dylib"]
